# fly.toml app configuration file generated for bot-compta on 2025-12-17T16:39:15Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#
app = "bot-compta"
primary_region = "cdg"

[build]
  builder = "paketobuildpacks/builder:base"

[processes]
  worker = "python3 bot.py"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory = "1gb"

